"use client"
import { useEffect, useState } from 'react'

type Device={id:string;label:string;android:string;sims:string;online:boolean;lastSeen:number}
type Event={id:string;deviceId:string;deviceLabel:string;appLabel:string;title:string;text:string;receivedAt:number}
export default function Home(){
 const [authed,setAuthed]=useState(false),[password,setPassword]=useState(''),[devices,setDevices]=useState<Device[]>([]),[events,setEvents]=useState<Event[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState('')
 async function load(){const r=await fetch('/api/dashboard',{cache:'no-store'});if(r.status===401){setAuthed(false);return}const d=await r.json();setAuthed(true);setDevices(d.devices||[]);setEvents(d.events||[])}
 async function login(){setLoading(true);setError('');const r=await fetch('/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password})});if(r.ok){setPassword('');await load()}else setError('Password salah');setLoading(false)}
 async function toggle(deviceId:string,value:boolean){await fetch('/api/control',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({deviceId,type:'forwarding_enabled',value})})}
 useEffect(()=>{load();const t=setInterval(load,5000);return()=>clearInterval(t)},[])
 if(!authed)return <main className="login"><div className="card"><div className="brand">SMS CONTROL</div><h1>Panel Notifikasi</h1><p>Private control panel</p><input type="password" placeholder="Admin password" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>e.key==='Enter'&&login()}/><button onClick={login} disabled={loading}>{loading?'Masuk…':'Masuk'}</button>{error&&<small>{error}</small>}</div></main>
 return <main className="shell"><header><div><span className="eyebrow">SMS CONTROL</span><h1>Notification Center</h1></div><button className="ghost" onClick={async()=>{await fetch('/api/auth/logout',{method:'POST'});setAuthed(false)}}>Keluar</button></header><section className="stats"><div><b>{devices.length}</b><span>Device</span></div><div><b>{devices.filter(d=>d.online).length}</b><span>Online</span></div><div><b>{events.length}</b><span>Event terbaru</span></div></section><section className="devices"><h2>Devices</h2>{devices.length===0?<div className="empty">Belum ada device terhubung.</div>:devices.map(d=><div className="device" key={d.id}><div><strong>{d.label}</strong><span>{d.android} · {d.sims||'SIM info unavailable'}</span></div><div className="deviceRight"><i className={d.online?'on':'off'}/><span>{d.online?'Online':'Offline'}</span><button onClick={()=>toggle(d.id,true)}>ON</button><button onClick={()=>toggle(d.id,false)}>OFF</button></div></div>)}</section><section className="events"><div className="sectionTitle"><h2>Notifikasi terbaru</h2><span>auto refresh 5s</span></div>{events.length===0?<div className="empty">Belum ada notifikasi.</div>:events.map(e=><article key={e.id}><div className="eventTop"><strong>{e.appLabel||e.title||'Notification'}</strong><time>{new Date(e.receivedAt).toLocaleString('id-ID')}</time></div><div className="muted">{e.deviceLabel}</div>{e.title&&<h3>{e.title}</h3>}<p>{e.text}</p></article>)}</section></main>
}
